import './globals.css'
import { Suspense } from 'react'
import { Inter } from 'next/font/google'
import Header from './components/Header'
const inter = Inter({ subsets: ['latin'] })
import { Roboto } from 'next/font/google'
import Footer from './components/Footer'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Suspense fallback={<p>Loading feed...</p>}>
      
      <Header name="Harish"  />
        {children}
      </Suspense>

        <Footer  />
        
        
        </body>
    </html>
  )
}
